apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd-system
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: crossplane 
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 01.12.2
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
