apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-tenant-2
  namespace: argocd-system
  labels:
    tenant-name: tenant-2
spec:
  destination:
    namespace: tenant-2
    server: https://kubernetes.default.svc
  project: tenants
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: tenants/tenant-2/resources/gcp
    repoURL: https://github.com/hosseinsalahi/kcd-multi-tenancy-vcluster-crossplane.git
    targetRevision: main
  syncPolicy:
    automated: {}
