apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-1
  namespace: argocd
spec:
  destination:
    namespace: tenant-1
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.15.2
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
